"""new migration

Revision ID: 0a9108af8616
Revises: ab8cb82fcfb7
Create Date: 2024-06-10 19:39:16.038406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "0a9108af8616"
down_revision: Union[str, None] = "ab8cb82fcfb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.alter_column("user", "referral_code", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "user",
        "date_of_birth",
        existing_type=sa.DATE(),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_column("user", "profile_pic_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("profile_pic_url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "user",
        "date_of_birth",
        existing_type=sa.DateTime(),
        type_=sa.DATE(),
        existing_nullable=True,
    )
    op.alter_column("user", "referral_code", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("user", "token")
    # ### end Alembic commands ###
